CCS Analysis

Comparison of carbon capture and storage (CCS) pathways for California under scenario 1 (coordinated) and scenario 2 (uncoordianted)


SETUP

In [1]:
import networkx as nx
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import hashlib
import scenario2Final as s2
import scenario1Final as s1

MONTE-CARLO FOR S1

In [2]:
sim1 = s1.monte_carlo(1000, sampling = True)

df1 = pd.DataFrame(sim1)
df1.head()

   rep  n_abandoned  completion
0    0            4       345.0
1    1            2       314.0
2    2            2       342.0
3    3            2       300.0
4    4            1       365.0

In [3]:
df1.describe()

               rep  n_abandoned   completion
count  1000.000000  1000.000000  1000.000000
mean    499.500000     1.167000   343.600000
std     288.819436     1.014959    31.194344
min       0.000000     0.000000   265.000000
25%     249.750000     0.000000   322.000000
50%     499.500000     1.000000   342.000000
75%     749.250000     2.000000   364.000000
max     999.000000     5.000000   469.000000

MONTE-CARLO FOR S2

In [4]:
sim2 = s2.monte_carlo(1000, sampling = True)

df2 = pd.DataFrame(sim2)
df2.head()

   rep  supply abandoned  transport abandoned  capture abandoned  completion
0    0                 3                    5                  9       246.0
1    1                 3                    5                  9       193.0
2    2                 3                    5                  9       223.0
3    3                 3                    5                  9       196.0
4    4                 4                    7                 12         0.0

In [5]:
df2.describe()

,rep,supply abandoned,transport abandoned,capture abandoned,completion
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,499.500000,3.271000,5.542000,9.813000,162.915000
std,288.819436,0.444699,0.889397,1.334096,101.257962
min,0.000000,3.000000,5.000000,9.000000,0.000000
25%,249.750000,3.000000,5.000000,9.000000,0.000000
50%,499.500000,3.000000,5.000000,9.000000,211.000000
75%,749.250000,4.000000,7.000000,12.000000,231.000000
max,999.000000,4.000000,7.000000,12.000000,340.000000