CCS Analysis

Comparison of carbon capture and storage (CCS) pathways for California under scenario 1 (coordinated) and scenario 2 (uncoordianted)


SETUP

In [7]:
import networkx as nx
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import hashlib
from Backend.models import scenario_2_final_refactored as s2
from Backend.models import scenario_1_final_refactored as s1

In [8]:
import importlib
importlib.reload(s1)
importlib.reload(s2)

MONTE-CARLO FOR S1

In [9]:
sim1 = s1.monte_carlo(1000, sampling = True)

df1 = pd.DataFrame(sim1)
df1.head()

   rep  num_cap  n_c_abandoned  completion  final volume
0    0        8              3       153.0      2.351458
1    1        8              2       142.0      3.362562
2    2        8              2       142.0      3.827851
3    3        8              2       153.0      3.955095
4    4        8              1       147.0      4.832409

In [10]:
df1.describe()

               rep  num_cap  n_c_abandoned   completion  final volume
count  1000.000000   1000.0    1000.000000  1000.000000   1000.000000
mean    499.500000      8.0       0.785000   148.645000      4.408296
std     288.819436      0.0       0.833949    11.807726      0.661332
min       0.000000      8.0       0.000000   112.000000      1.238846
25%     249.750000      8.0       0.000000   140.000000      3.881742
50%     499.500000      8.0       1.000000   148.000000      4.832409
75%     749.250000      8.0       1.000000   156.000000      4.892846
max     999.000000      8.0       4.000000   195.000000      4.892846

MONTE-CARLO FOR S2

In [11]:
sim2 = s2.monte_carlo(1000, sampling = True)

df2 = pd.DataFrame(sim2)
df2.head()

,rep,num_stor,storage abandoned,num_trans,transport abandoned,num_cap,capture abandoned,completion,final volume
0,0,1,1,1,1,8,8,0.0,0.000000
1,1,1,1,1,1,8,8,0.0,0.000000
2,2,1,0,1,0,8,2,81.0,4.718995
3,3,1,0,1,0,8,2,85.0,3.665669
4,4,1,1,1,1,8,8,0.0,0.000000

In [12]:
df2.describe()

,rep,num_stor,storage abandoned,num_trans,transport abandoned,num_cap,capture abandoned,completion,final volume
count,1000.000000,1000.0,1000.000000,1000.0,1000.000000,1000.0,1000.000000,1000.0000,1000.000000
mean,499.500000,1.0,0.240000,1.0,0.240000,8.0,2.561000,61.3770,3.391922
std,288.819436,0.0,0.427297,0.0,0.427297,0.0,3.138492,35.0241,1.965021
min,0.000000,1.0,0.000000,1.0,0.000000,8.0,0.000000,0.0000,0.000000
25%,249.750000,1.0,0.000000,1.0,0.000000,8.0,0.000000,68.0000,3.308434
50%,499.500000,1.0,0.000000,1.0,0.000000,8.0,1.000000,78.0000,4.273423
75%,749.250000,1.0,0.000000,1.0,0.000000,8.0,3.000000,83.0000,4.892846
max,999.000000,1.0,1.000000,1.0,1.000000,8.0,8.000000,104.0000,4.892846