CCS Analysis

Comparison of carbon capture and storage (CCS) pathways for California under scenario 1 (coordinated) and scenario 2 (uncoordianted)


SETUP

In [ ]:
import networkx as nx
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import hashlib
import world_2_edits as s2
import scenario_1_methods as s1

AttributeError: module 'project_data' has no attribute 'CLUSTERS'

In [ ]:
import importlib
importlib.reload(s1)
importlib.reload(s2)

MONTE-CARLO FOR S1

In [ ]:
sim1 = s1.monte_carlo(1000, sampling = True)

df1 = pd.DataFrame(sim1)
df1.head()

,c_abandon,rep,num_cap,n_c_abandoned,completion,final volume
0,"{'projC1': 'approval', 'projC2': 'approval', '...",0,8,5,143.0,0.997037
1,"{'projC1': 'definition', 'projC2': 'approval',...",1,8,3,142.0,2.249950
2,"{'projC2': 'approval', 'projC3': 'approval', '...",2,8,3,131.0,2.715239
3,"{'projC3': 'approval', 'projC4': 'approval', '...",3,8,4,153.0,2.702182
4,{'projC5': 'definition'},4,8,1,147.0,4.832409

In [ ]:
df1.describe()

               rep  num_cap  n_c_abandoned   completion  final volume
count  1000.000000   1000.0    1000.000000  1000.000000   1000.000000
mean    499.500000      8.0       1.995000   146.780000      3.625435
std     288.819436      0.0       1.241175    11.997647      1.027003
min       0.000000      8.0       0.000000   103.000000      0.173851
25%     249.750000      8.0       1.000000   139.000000      2.943991
50%     499.500000      8.0       2.000000   147.000000      3.764598
75%     749.250000      8.0       3.000000   154.000000      4.717844
max     999.000000      8.0       6.000000   195.000000      4.892846

MONTE-CARLO FOR S2

In [ ]:
sim2 = s2.monte_carlo(1000, sampling = True)

df2 = pd.DataFrame(sim2)
df2.head()

,a_c,a_t,a_s,rep,num_stor,storage abandoned,num_trans,transport abandoned,num_cap,capture abandoned,completion,final volume
0,"{'projC2': 'definition', 'projC1': 'approval',...",{'projT1': 'approval'},{'projS1': 'approval'},0,1,1,1,1,8,8,0.0,0.000000
1,"{'projC1': 'definition', 'projC2': 'definition...",{'projT1': 'definition'},{'projS1': 'approval'},1,1,1,1,1,8,8,0.0,0.000000
2,"{'projC6': 'definition', 'projC8': 'definition'}",{},{},2,1,0,1,0,8,2,81.0,4.718995
3,"{'projC6': 'definition', 'projC2': 'approval'}",{},{},3,1,0,1,0,8,2,85.0,3.665669
4,"{'projC1': 'definition', 'projC2': 'definition...",{'projT1': 'definition'},{'projS1': 'approval'},4,1,1,1,1,8,8,0.0,0.000000

In [ ]:
df2.describe()

,rep,num_stor,storage abandoned,num_trans,transport abandoned,num_cap,capture abandoned,completion,final volume
count,1000.000000,1000.0,1000.000000,1000.0,1000.000000,1000.0,1000.000000,1000.0000,1000.000000
mean,499.500000,1.0,0.240000,1.0,0.240000,8.0,2.561000,61.3770,3.391922
std,288.819436,0.0,0.427297,0.0,0.427297,0.0,3.138492,35.0241,1.965021
min,0.000000,1.0,0.000000,1.0,0.000000,8.0,0.000000,0.0000,0.000000
25%,249.750000,1.0,0.000000,1.0,0.000000,8.0,0.000000,68.0000,3.308434
50%,499.500000,1.0,0.000000,1.0,0.000000,8.0,1.000000,78.0000,4.273423
75%,749.250000,1.0,0.000000,1.0,0.000000,8.0,3.000000,83.0000,4.892846
max,999.000000,1.0,1.000000,1.0,1.000000,8.0,8.000000,104.0000,4.892846