CCS Analysis

Comparison of carbon capture and storage (CCS) pathways for California under scenario 1 (coordinated) and scenario 2 (uncoordianted)


SETUP

In [8]:
import networkx as nx
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import hashlib
from Backend.models import scenario_2_final_refactored as s2
import scenario_1_final as s1

In [9]:
import importlib
importlib.reload(s1)
importlib.reload(s2)

MONTE-CARLO FOR S1

In [ ]:
sim1 = s1.monte_carlo(1000, sampling = True)

df1 = pd.DataFrame(sim1)
df1.head()

                           0
0    average no. abandoned:
1                      1.167
2  average completion time:
3                      343.6
4     average final volume:

In [11]:
df1.describe()

                              0
count                         6
unique                        6
top     average no. abandoned:
freq                          1

MONTE-CARLO FOR S2

In [ ]:
sim2 = s2.monte_carlo(1000, sampling = True)

df2 = pd.DataFrame(sim2)
df2.head()

                                    0
0     average no. capture abandoned:
1                               9.813
2  average capture abandonment rate:
3                             0.81775
4   average no. transport abandoned:

In [13]:
df2.describe()

               0
count   20.00000
unique  19.00000
top      0.81775
freq     2.00000